development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: livecookie@gmail.com
  :password: zacks198871
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: livecookie@gmail.com
  :password: zacks198871
  :enable_starttls_auto: true